name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: 1.20.2
      - name: Check format
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run test
        run: deno test --allow-read --allow-write
